services:
  app_market:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: laravel-market
    volumes:
      - .:/var/www
    restart: unless-stopped
    depends_on:
      - db_market
  
  # Nginx Service
  market_nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "9006:80"
    volumes:
      - .:/var/www
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/

  # mysql
  db_market:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: market
    volumes:
      - dbdatamarket:/var/lib/mysql
    ports:
      - 3306:3306

  # admin mysql
  adminer-inter:
    image: adminer
    restart: unless-stopped
    ports:
      - 8096:8080
    environment:
      - ADMINER_DESIGN=dracula
    depends_on:
      - db_market

volumes:
  dbdatamarket:
